
_target_: src.datamodule.pubtabnet.PubTabNet
root_dir: /raid/speng65/MISC/PubTabNet/examples
label_type: ${dataset.label_type}
split: train
json_html: clean_html_PubTabNet_Examples.jsonl
transform: ${dataset.augmentation}
cell_limit: 150