_target_: torchvision.datasets.ImageFolder
root: /raid/speng65/DATASETS/imagenet/val
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.CenterCrop
      size: ${trainer.img_size}
    - _target_: torchvision.transforms.ToTensor